// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function EndProcess(arg1:number,arg2:boolean):Promise<void>;

export function Snapshot():Promise<main.Snapshot>;
