// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppIcon(arg1) {
  return window['go']['main']['App']['AppIcon'](arg1);
}

export function EndGroup(arg1, arg2) {
  return window['go']['main']['App']['EndGroup'](arg1, arg2);
}

export function EndProcess(arg1, arg2, arg3) {
  return window['go']['main']['App']['EndProcess'](arg1, arg2, arg3);
}

export function OpenLocation(arg1, arg2) {
  return window['go']['main']['App']['OpenLocation'](arg1, arg2);
}

export function ProcessDetail(arg1, arg2) {
  return window['go']['main']['App']['ProcessDetail'](arg1, arg2);
}

export function SetPriority(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetPriority'](arg1, arg2, arg3);
}

export function SignalProcess(arg1, arg2, arg3) {
  return window['go']['main']['App']['SignalProcess'](arg1, arg2, arg3);
}

export function Snapshot() {
  return window['go']['main']['App']['Snapshot']();
}
