// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EndProcess(arg1, arg2) {
  return window['go']['main']['App']['EndProcess'](arg1, arg2);
}

export function Snapshot() {
  return window['go']['main']['App']['Snapshot']();
}
