// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AppIcon(arg1:string):Promise<any>;

export function EndGroup(arg1:string,arg2:boolean):Promise<void>;

export function EndProcess(arg1:number,arg2:number,arg3:boolean):Promise<void>;

export function OpenLocation(arg1:number,arg2:number):Promise<void>;

export function ProcessDetail(arg1:number,arg2:number):Promise<main.ProcessInfo>;

export function SetPriority(arg1:number,arg2:number,arg3:number):Promise<void>;

export function SignalProcess(arg1:number,arg2:number,arg3:string):Promise<void>;

export function Snapshot():Promise<main.Snapshot>;
